### ISSUE TITLE
Crash when loading world with Extended Clouds

### ISSUE THREAD

**Issue by Rivmun** [fxmorin/MoreCulling#133] opened 2023-01-11 12:48 UTC
Hi, I've got some crash when I add More Culling to my modpack. Game window will flash into white and shutdown when I enter a world (load/create either) after "loading terrain...".
I tested 0.13.0 and 0.12.5 and nothing change even crash-reports' message.
Then I only load More Culling on same loader (Fabric-0.14.10). It works perfectly.
So, I guess there is something conflict with More Culling I can't figure out, because the mod list is a little bit long...
Crash report here: 
[crash-2023-01-11_18.16.04-client.txt](https://github.com/fxmorin/MoreCulling/files/10392281/crash-2023-01-11_18.16.04-client.txt)

btw 0.10.1 (one ahead 0.12.x on 1.19.2) seems working good in my pack. But I want latest for more culling function.

**Comment by fxmorin** [comment] 2023-01-11 15:37
How on earth am I suppose to debug this xD.
I think the bug is caused by: `extended-clouds` doing async rendering which breaks the buffer. Although honestly that buffer should be faster to render than the async code so idk...

Either way, try disabling cloud culling and trying again

**Comment by Rivmun** [comment] 2023-01-11 16:59
Oh, it's works after cloud culling was disabled! Thanks for your patience to that blurry issue.
(Finally, I resolve to remove Extended Clouds due to it bad compatibility.)

**Comment by fxmorin** [comment] 2023-01-11 22:57
I'll add mod incompatibility then close it so others don't have the same issue

**Closed** 2023-01-27 01:03 UTC
