### ISSUE TITLE
Shulker planes showing when placed in front of carpet

### ISSUE THREAD

**Issue by dojofemy** [fxmorin/MoreCulling#132] opened 2023-01-07 22:56 UTC
![1](https://user-images.githubusercontent.com/48302930/211173237-40521d84-fce8-4894-abf4-b26ffd2565fb.png)
![2](https://user-images.githubusercontent.com/48302930/211173238-2655de73-d252-4479-af61-3ea7dc6b7df6.png)

Just installed the mod and loaded up my world. I then looked at the box displays which have carpets in front of them. 

This is how it looked. It's just the planes of the shulkers showing.. but it fixes itself when I remove the carpets.

Thought I would report it here.

**Comment by Kikugie** [comment] 2023-01-07 23:02
Duplicate of #131

**Comment by fxmorin** [comment] 2023-01-11 22:42
Fixed in v0.14.0

**Closed by fxmorin** 2023-01-11 22:42 UTC
