### ISSUE TITLE
Pose stack not empty crash

### ISSUE THREAD

**Issue by Defetyre** [fxmorin/MoreCulling#121] opened 2022-12-27 08:33 UTC
Upon entering one of my worlds, the game immediately crashes. Removing your mod prevents the crash.

https://mclo.gs/jtQwQAG

**Comment by Foxlass** [comment] 2022-12-28 09:29
Same issue here

**Comment by MasterMCerGH** [comment] 2022-12-28 22:12
same

**Comment by cerealconjugo** [comment] 2022-12-29 00:43
Same, it's strange because i have been using it a while ago and it's the first time it starts to present this issue

**Comment by MasterMCerGH** [comment] 2022-12-29 18:58
did you update to 1.19.2?

**Comment by Firestrike1** [comment] 2022-12-29 22:16
I remember using it for quite some time on both 1.18.2 and 1.19.2 before this happened

**Comment by MasterMCerGH** [comment] 2022-12-30 03:44
fabric or quilt?

**Comment by ChristopherHaws** [comment] 2022-12-30 04:42
Fabric

**Comment by Defetyre** [comment] 2022-12-30 06:54
Happens on Quilt too

**Comment by fxmorin** [comment] 2022-12-30 08:48
I'm back from vacation so I will attempt to fix this tomorrow

**Comment by fxmorin** [comment] 2022-12-30 20:13
Can everyone here give me there mods list. Seems to be a mod compatibility issue

**Comment by fxmorin** [comment] 2022-12-30 20:16
This is a duplicate of #118, you can fix it by disabling sign culling until I fix the issue

**Closed by fxmorin** 2022-12-30 20:16 UTC

**Comment by cerealconjugo** [comment] 2022-12-30 21:53
- Advancement Plaques 
- Allay in a bottle
-  Architectury
- Blast travel
- Carry On
- Catalogue
- Cloth Config
- Companion
- Configured
- Create
- Explorify
- Farmer's Delight
- Ferrite Core
- Fish of thieves
- Forge config api Port
- Geckolib
- Geophilic
- Goblin Traders
- Highlighter
- HT's TreeChop
- Iceberg
- ImmediatelyFast
- Indium
- Inspecio
- Keymap
- Krypton
- Lithium
- LookAtMyStuff
- Memory Leak Fix
- Menulogue
- Merchant Markers
- ModelGapFix
- Moonlight Lib
- More Culling --
- Nicer skies
- Pettable
- Profundis
- Quick Shulker
- Quilt Kotlin libraries
- Quilt Loading screen
- Quilted Fabric API
- Rainbowify
- Rat's Mischief
- Repurposed structures
- REI
- Screenshot Viewer
- Smarther Farmers
- Sodium 
- Starlight
- Supplementaries
- Tooltip Fix
- Visuality
- YetAnotherConfigLib
- Zoomify

By the time at the crash i removed this mods wondering if of those where the problem:
-Falling Leaves
-EnchantwithMob
-ParticleRain

I tried to reproduced it to give you a log but im unable to reproduce the crash in the same scenario, let me install those mods again to see if one of those its causing the crash.

**Comment by cerealconjugo** [comment] 2022-12-30 21:58
Oh I see it's fixed now, thanks.
