### ISSUE TITLE
Weird issue when using MoreCulling and Vanilla Tweaks Bushy Leaves resourcepack

### ISSUE THREAD

**Issue by mvilk** [fxmorin/MoreCulling#114] opened 2022-12-18 16:05 UTC
I'm using MoreCulling with [Vanilla Tweaks Bushy Leaves (download link)](https://vanillatweaks.net/share#Fc71k5) resourcepack and blocks behind leaves don't render at all. I can see through walls as shown in the image below.

Info:
Minecraft version: 1.19.3
MoreCulling version: 1.19.3-0.12.2
I have not modified any settings of MoreCulling.
Resourcepack: [Vanilla Tweaks Bushy Leaves (download link)](https://vanillatweaks.net/share#Fc71k5)

EDIT: I did some testing and seems like this started to happen in version 1.19.3-0.12.0

![2022-12-18_17 39 04](https://user-images.githubusercontent.com/75657829/208307247-27f77ac4-8ad7-4978-b64c-9feab8325741.png)

**Comment by fxmorin** [comment] 2022-12-19 16:17
Thanks for reporting it, I believe this is due to a change in how I handle MultiPart models now.
Before if the model had any part that had transparency (including the small bushy leaves) it would not cull behind it. Although now its smarter and can determine the difference, however leaves are very weird when it comes to culling.

Could you tell me what leave culling options you have selected, what graphics mode you are on, and if you are using sodium?

**Comment by fxmorin** [comment] 2022-12-19 17:08
I was not able to reproduce this using sodium and moreculling, with any leaves setting. Are you using any shaders?

**Comment by fxmorin** [comment] 2022-12-19 18:09
Oboi Why does it not happen to me than. I don't like that...
Any other resource packs?

**Comment by fxmorin** [comment] 2022-12-19 18:31
I was able to recreate it, it's when you run MoreCulling without fabric API. I'll attempt to fix it

**Comment by fxmorin** [comment] 2022-12-19 19:12
Should be fixed in latest release v0.12.3
https://github.com/fxmorin/MoreCulling/releases

**Closed by fxmorin** 2022-12-19 19:12 UTC
